//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trabMasterPage {
	
	
	public partial class Inicio {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.WebControls.HyperLink linkServ;
		
		protected System.Web.UI.WebControls.HyperLink linkNovo;
		
		protected System.Web.UI.WebControls.HyperLink linkLogin;
		
		protected System.Web.UI.WebControls.HyperLink linkLogoff;
		
		protected System.Web.UI.WebControls.Label lblNome;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder conteudoCentral;
	}
}
